### ISSUE TITLE
Gettig java.lang.NoClassDefFoundError: com.google.firebase.FirebaseOptions error

### ISSUE THREAD

**Issue by sztankatt** [smartdevicelink/sdl_mobileweather_tutorial_android#5]
Hey!

I am getting `java.lang.NoClassDefFoundError: com.google.firebase.FirebaseOptions` error for this application when I try to deploy it to an android (4.4.4). The application icon is there, but If try to open it it does not open and I get the above error in Android Studio.

I have Google Play installed (version 31).

Could you advise me on this?

**Comment by sztankatt** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.ford.mobileweather, PID: 29772
                                                                        java.lang.NoClassDefFoundError: com.google.firebase.FirebaseOptions
                                                                            at com.google.firebase.FirebaseApp.zzeh(Unknown Source)
                                                                            at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                            at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
                                                                            at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
                                                                            at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:4908)
                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4503)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4443)
                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:212)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                            at dalvik.system.NativeStart.main(Native Method)`

here is the whole trace

**Comment by asm09fsu** [comment]
This seems to be an issue related to Firebase, not SDL.

**Comment by sztankatt** [comment]
Okay. Closig it then.

**Comment by sztankatt** [comment]
By the way, which version of google_play_services are you using? I am usig 9.2.0

**Comment by Adhamsheriff** [comment]
Hi,
Any fix this solution?
